version: "3.9"

services:
  backend:
    build: ./Backend
    ports:
      - "80:1337"
    volumes:
      - ./Backend:/app/Backend
      - ./logs/Backend:/app/Backend/logs
    networks:
      - backend-network
      - elevator-network
    restart:
      unless-stopped

  elevator:
    build: ./ElevatorBot
    volumes:
      - ./ElevatorBot:/app/ElevatorBot
      - ./logs/ElevatorBot:/app/ElevatorBot/logs
    networks:
      - backend-network
      - elevator-network
      - website-network
    restart:
      unless-stopped
    depends_on:
      - backend
      - website

  website:
    build: Website
    ports:
      - "80:80"
    volumes:
      - ./Website:/app/Website
      - ./logs/Website_old:/app/Website_old/logs
    networks:
      - backend-network
      - website-network
    restart:
      unless-stopped
    depends_on:
      - backend
    

networks:
  backend-network:
  elevator-network:
  website-network:

# https://www.docker.com/blog/containerized-python-development-part-2/