version: "3.9"

services:
  postgres:
    image: postgres:13.5-bullseye
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./Database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    networks:
      - database-network
    restart:
      always

  postgresbackups:
    image: prodrigestivill/postgres-backup-local
    volumes:
      - ./DatabaseBackups:/backups
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - POSTGRES_PORT
      - SCHEDULE=@weekly
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
    networks:
      - database-network
    restart:
      always
    depends_on:
      - postgres

  backend:
    build: ./Backend
    ports:
      - "${BACKEND_PORT}:8000"
    volumes:
      - ./Backend:/app/Backend
      - ./Logs/Backend:/Logs/Backend
      - ./settings.py:/app/settings.py
      - ./NetworkingSchemas:/app/NetworkingSchemas
      - ./DestinyEnums:/app/DestinyEnums
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - POSTGRES_PORT
      - BACKEND_HOST
      - BACKEND_PORT
      - ELEVATOR_HOST
      - ELEVATOR_PORT
    networks:
      - database-network
      - backend-network
    restart:
      unless-stopped
    depends_on:
      - postgres
      - postgresbackups

  website:
    build: Website
    ports:
      - "${WEBSITE_PORT}:3000"
    volumes:
      - ./Website:/app/Website
      - ./ElevatorBot/docs:/app/ElevatorBot/docs
      - ./Logs/Website:/app/Logs/Website
    environment:
      - BACKEND_HOST
      - BACKEND_PORT
      - WEBSITE_HOST
      - WEBSITE_PORT
      - ELEVATOR_HOST
      - ELEVATOR_PORT
    networks:
      - backend-network
      - website-network
    restart:
      unless-stopped
    depends_on:
      - backend

  elevator:
    build: ./ElevatorBot
    ports:
      - "${ELEVATOR_PORT}:8080"
    volumes:
      - ./ElevatorBot:/app/ElevatorBot
      - ./Logs/ElevatorBot:/app/Logs/ElevatorBot
      - ./settings.py:/app/settings.py
      - ./NetworkingSchemas:/app/NetworkingSchemas
      - ./DestinyEnums:/app/DestinyEnums
      - ./version.py:/app/version.py
    environment:
      - BACKEND_HOST
      - BACKEND_PORT
      - WEBSITE_HOST
      - WEBSITE_PORT
      - ELEVATOR_HOST
      - ELEVATOR_PORT
    networks:
      - backend-network
      - elevator-network
      - website-network
    restart:
      unless-stopped
    depends_on:
      - backend
      - website


networks:
  backend-network:
  elevator-network:
  website-network:
  database-network:
