[tool.black]
line-length = 120
target-version = ["py310"]
include = '(^.*\/ElevatorBot\/.*.py$)|(^.*\/Backend\/.*.py$)'

[tool.isort]
line_length = 120
py_version = 310
profile = "black"
multi_line_output = 3
filter_files = true
