version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
#    container_name: prometheus
    restart: unless-stopped
    expose:
      - 9090
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

  grafana:
    image: grafana/grafana:latest
#    container_name: grafana
    restart: unless-stopped
    expose:
      - 3000
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini

  discord-bot:
#    container_name: discord-bot
    build: .
    command: python main.py
    restart: unless-stopped
    expose:
      - 8877
    env_file:
      - .env.bot

volumes:
  prometheus_data:
  grafana_data:
