name: Create Release

on:
  push:
    branches:
      - master
    paths:
      - version.py

jobs:
  release:
    name: Release

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Version from "version.py"
        id: version
        run: echo ::set-output name=version::$(cat version.py| sed 's/"/\n/2' | cut -c 16-)

      - name: Generate Changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.version }}
          release_name: Release v${{ steps.vars.outputs.version }}
          body: ${{steps.changelog.outputs.changelog}}
          draft: false
          prerelease: true
