name: Create Release

on:
  push:
    branches:
      - master
    paths:
      - version.py

jobs:
  release:
    name: Release

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Version from "version.py"
        id: vars
        run: echo ::set-output name=version::$(cat version.py| cut -c 16- | rev | cut -c 3- | rev)

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.vars.outputs.version }}
          release_name: Release v${{ steps.vars.outputs.version }}
          draft: false
          prerelease: true
