name: Black Formating

on:
  push:
    branches:
    - master
    paths:
    - ElevatorBot/**/*.py
  pull_request:
    branches:
    - master
    paths:
    - ElevatorBot/**/*.py

jobs:
  black:
    name: Black

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Format with Black
        uses: rickstaa/action-black@v1
        with:
          black_args: "ElevatorBot"
