name: ElevatorBot

on:
  push:
    branches:
    - master
    paths:
    - ElevatorBot/**/*.py
  pull_request:
    branches:
    - master
    paths:
    - ElevatorBot/**/*.py

jobs:
  python-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Set Up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
      
    - name: Install Python Requirements
      run: |      
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: ElevatorBot
      
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 --count --exit-zero --max-complexity=10 --max-line-length=999 --statistics
      working-directory: ElevatorBot
      
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
      working-directory: ElevatorBot
