name: Test Backend

on:
  push:
    branches:
    - master
    paths:
    - Backend/**/*.py
  pull_request:
    branches:
    - master
    paths:
    - Backend/**/*.py

jobs:
  python-tests:
    name: Test Backend

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Python Requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: Backend

    - name: Test with pytest
      run: |
        # install pytest and useful wrappers
        pip install pytest
        pip install pytest-asyncio
        pip install pytest_mock
        pip install aiosqlite
        pip install httpx

        # make sure the db runs
        docker-compose run -d --service-ports postgres

        # add the env varible we need to connect to the db
        export $(grep -v '^#' .env | xargs -d '\n')

        # add the dir to pythonpath
        export PYTHONPATH="${PYTHONPATH}:/home/runner/work/elevatorbot"

        # rename the settings file
        sudo mv rename_to_settings.py settings.py

        # run tests
        pytest Backend
