name: Website

on:
  push:
    branches:
    - master
    paths:
    - Backend/**
  pull_request:
    branches:
    - master
    paths:
    - Backend/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Install Dependencies
      run: npm install
      working-directory: Website

    - name: Run Tests
      run: npm test
      working-directory: Website

    - name: Build
      run: npm run build
      working-directory: Website

